### ISSUE TITLE
items not displaying in hand 

### ISSUE THREAD

**Issue by KnightRaven45** [Mine-Treasure/mine-treasure#13]
![2024-07-13_19 50 50](https://github.com/user-attachments/assets/e7e5e024-3cba-4ce8-b7e3-905b102f1fd5)
![2024-07-13_19 50 50](https://github.com/user-attachments/assets/7085f65b-aac7-4c8d-bd15-232168f75652)

**Comment by Frozeh** [comment]
Mine Treasure does not affect anything related to displaying an item, this is another mod.
