### ISSUE TITLE
Bug - Wrong treasure spawning

### ISSUE THREAD

**Issue by Heretic-117** [Mine-Treasure/mine-treasure#3]
Im playing on 1.19.2 with 1.2.8 mine treasure mod version.

Was playing and i noticed that Terralith:Caldera region doesn't give Moutain or Taiga treasure like its write on the table loot. 
And btw it's possible to have 2 or more different treasure for a region ? 

First time noticing it so not sure if its a normal behaviour or due to other things.

**Comment by Frozeh** [comment]
Sorry for the late response. But this isn't under my control, you can now change biomes easily by going into `data/mt/tags/worldgen/biome` and changing the biomes there yourself.
